const mongoose=require('mongoose');
const ExtrasSchema = require('./ExtrasSchema');


const inningsSchema=mongoose.Schema({
    match_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Match',
        required:true   
    },
    battingTeam:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Playing11',
        required:true
    },
    bowlingTeam:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Playing11',
        required:true
    },
    Runs:{
        type:Number,
        default:0
    },
    Wickets:{
        type:Number,
        default:0
    },
    Overs:{
        type:Number,
        default:0
    },
    Balls:{
        type:Number,
        default:0
    },
    Extras:{
        type:ExtrasSchema,
        default:()=>({})
    },
    runRate:{
        type:Number,
        default:0
    },
    requiredRunRate:{
        type:Number,
        default:0
    },
    Boundaries:{
        type:Number,
        default:0
    },
    Sixes:{
        type:Number,
        default:0
    },
    BattingScorecard:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'BattingScore',
            required:true
        }
    ],
    BowlingScorecard:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'BowlingScore',
            required:true
        }
    ],
    isCompleted:{
        type:Boolean,
        default:false
    }
},
{
    timestamps:true
});

const InningsModel=mongoose.model('Innings',inningsSchema);
module.exports=InningsModel;