const mongoose=require('mongoose');

TeamStatisticsSchema={
    matches_played:{
        type:Number,
        default:0
    },
    wins:{
        type:Number,
        default:0
    },
    losses:{
        type:Number,
        default:0
    },
    draws:{
        type:Number,
        default:0
    },
    no_result:{
        type:Number,
        default:0
    }
}

const TeamSchema=mongoose.Schema({
    team_name:{
        type:String,
        required:true
    },
    team_logo:{
        type:String,
        required:true
    },
    team_captain:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Player',
    },
    team_viceCaptain:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Player',
    },
    team_wicketKeeper:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Player',
    },  
    team_manager:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'TeamManager',
    },
    team_players:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Player',
    }],
    team_home:{
        type:String,
    },
    team_description:{
        type:String,
    },
    team_trophies_won:{
        type:Number,
        default:0
    },
    playing11:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Player',
        required:true
    }],
    tournaments_won:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Tournament',
    },
    isDeleted:{
        type:Boolean,
        default:false
    },
    statistics:{
        T20I:TeamStatisticsSchema,
        ODI:TeamStatisticsSchema,
        Test:TeamStatisticsSchema,
        Domestic_T20:TeamStatisticsSchema,
        Domestic_ODI:TeamStatisticsSchema,
        Domestic_Test:TeamStatisticsSchema
    }
})

const TeamModel=mongoose.model('Team',TeamSchema);
module.exports=TeamModel;